### ISSUE TITLE
doesn't work with new node-fetch

### ISSUE THREAD

**Issue by mienaikoe** [qubyte/fetch-ponyfill#10]
Hey there. I'm using fetch-ponyfill 1.0.0   with  node-fetch 1.5.1
When I try to run my tests, I get this error:
   TypeError: Fetch.Promise is not a function

I looked into the source of node-fetch, and they recently added the notion of the Fetch class, which requires Promise to be an attribute of Fetch. The current implementation of fetch-ponyfill only applies this to fetch (lowercase). Want a PR for it?

**Comment by qubyte** [comment]
This library is intended to be a thin wrapper around the browser fetch-polyfil first, and isomorphic second. That being said, I'd like to see a reduction to see this behaviour in action. Could you show me how to reproduce this please?

**Comment by mienaikoe** [comment]
I've made a gist:

https://gist.github.com/mienaikoe/adc59f9e72e98c287498318a96998f33

**Comment by mienaikoe** [comment]
my npm dependency list for this is:

  "dependencies": {
    "es6-promise": "^3.2.1",
    "fetch-ponyfill": "^1.0.0"
  }

**Comment by paulmelnikow** [comment]
Are this library's current tests reproducing the problem with the affected version of node-fetch?

**Comment by mienaikoe** [comment]
Tests run fine as they are. In the tests, I tried replacing 'promise' with 'es6-promise', and I got the same error. I believe this is because 'es6-promise' does not replace the global Promise with itself unless you ask it to do so. 'promise' probably does. 

In node-fetch, you can see where it sets Fetch.Promise to be whatever global.promise is. If global promise doesn't exist, then this will remain as undefined.

The problem arises in the setting of "fetch.Promise", which does nothing. if you want to make a difference to node-fetch, you should be using "Fetch.Promise"

**Comment by paulmelnikow** [comment]
Ah, the problem is in your `require`. It looks like you need to change
```js
Promise: require('es6-promise')
```
to 
```js
Promise: require('es6-promise').Promise
```

**Comment by qubyte** [comment]
@mienaikoe did @paulmelnikow's suggestion help?

**Comment by mienaikoe** [comment]
Yea. Realized that requiring es6-promise just puts it into the global scope. Paul's suggestion actually assigns it. Closing.
