### ISSUE TITLE
Headers, Response and Request classes

### ISSUE THREAD

**Issue by benjamine** [qubyte/fetch-ponyfill#11]
maybe I'm missing something, but these classes seem to be necessary to use fetch, and would depend on the ponyfilled implementation.

eg. see https://github.com/matthew-andrews/isomorphic-fetch/commit/79e536867baa9f8788218cf028f81fb05324bcee

**Comment by paulmelnikow** [comment]
Interesting, I've never needed to use those classes directly…

**Comment by benjamine** [comment]
@paulmelnikow are you just sending headers as a plain object? IDK, maybe that works in some implementations (it would be nice if that were the official API :( ).

**Comment by qubyte** [comment]
Thanks for raising this. I'll take a look at the next opportunity (might be a few days). If you need this feature sooner, pull requests are most welcome! :)

FWIW The raw classes are rarely necessary to use fetch, although I have used them and they are part of the spec.

**Comment by benjamine** [comment]
sweet!, thanks!
