### ISSUE TITLE
None of the support seems to be detected properly

### ISSUE THREAD

**Issue by divoxx** [qubyte/fetch-ponyfill#15]
Every support detection fails because self is set to an blank object:

https://github.com/github/fetch/blob/master/fetch.js#L9-L20

For example, using any of the supported body types such as FormData is currently not working.

**Comment by qubyte** [comment]
Thanks for flagging this. I've opened a PR to fix (#16). I want to sleep on it to see if I can think of a good way to test it before merging though.

**Comment by divoxx** [comment]
@qubyte no problem! Thanks for the fast response!
