### ISSUE TITLE
Suggest adding `types` property to package.json

### ISSUE THREAD

**Issue by robations** [qubyte/fetch-ponyfill#161]
Note this isn't technically a problem with this package, but might ease some issues with Jetbrains IDEs, which don't seem to be picking up type definitions from fetch-ponyfill at the moment.

I would suggest adding the following line to `package.json`:

    "types": "./index.d.ts"

See here:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000071990-Does-intellij-IDEA-need-index-d-ts-to-import-from-package-

> But you have to make sure that your index.ts file is specified in your 'common' module package.json as either "typings" or "types" value

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> if your main declaration file is named index.d.ts and lives at the root of the package (next to index.js) you do not need to mark the "types" property, though it is advisable to do so

**Comment by robations** [comment]
(Can submit a PR if you think makes sense to add this.)

**Comment by qubyte** [comment]
Apologies for the late response. I'd welcome a PR!

**Comment by qubyte** [comment]
Released with v6.1.0.

**Comment by robations** [comment]
> Can submit a PR

Sorry, this got away from me, and thanks.

You might want to push the source code for 6.1.0. npm packages where the latest source code has disappeared from view has to be considered a risk factor, after the [incident](https://www.trendmicro.com/vinfo/dk/security/news/cybercrime-and-digital-threats/hacker-infects-node-js-package-to-steal-from-bitcoin-wallets) last year.

**Comment by qubyte** [comment]
My bad. Code and tag pushed.
