### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by colin-air** [qubyte/fetch-ponyfill#18]
It would be great if releases had the the very least a TL;DR. Going through the commits from one version to the next obviously provides all of the necessary details, but it would be nice to have a summary

**Comment by qubyte** [comment]
There is a history file with a very brief TL;DR. Is there anything in particular you need to know?

**Comment by qubyte** [comment]
(I'll include any github/fetch version bumps in the history file in future releases. Thanks for the reminder.)

**Comment by colin-air** [comment]
I somehow missed the history file!
