### ISSUE TITLE
Abort support

### ISSUE THREAD

**Issue by jack-sf** [qubyte/fetch-ponyfill#185]
Have you thought about adding support also for aborting the reqeusts? ( https://developer.mozilla.org/en-US/docs/Web/API/AbortController/abort )

On browser environment, we could use have a ponyfill similar to this polyfill: https://github.com/mo/abortcontroller-polyfill .

On node environment, node-fetch seems to already support AbortController: https://github.com/bitinn/node-fetch/issues/95 .

So this fetch-ponyfill could also ponyfill the abortcontroller, and export `AbortController` and `AbortSignal`. WDYT?

**Comment by qubyte** [comment]
I see no need. It looks like abortcontroller-polyfill is already usable as a ponyfill already, and when node-fetch supports abort, it'll get into this library naturally as dependencies are updated.
