### ISSUE TITLE
Can't install library

### ISSUE THREAD

**Issue by kruszyk** [qubyte/fetch-ponyfill#190]
Whenever I try to run 

`npm i fetch-ponyfill `

I get 

`npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/ms-rest-js/fetch-ponyfill@github:amarzavery/fetch-ponyfill#136e6f8192bdb2aa0b7983f0b3b4361c357be9db" as it does not contain a package.json file.
`

**Comment by qubyte** [comment]
Looking at that error, this appears to be an issue elsewhere. First, that error references [`ms-rest-js`](https://www.npmjs.com/package/ms-rest-js), which is a deprecated package (renamed). Next, `ms-rest-js` appears to be referencing a [_fork_ of this repository](https://github.com/amarzavery/fetch-ponyfill). I recommend updating the former. It'll probably fix this issue.
