### ISSUE TITLE
Use native fetch if it's supported

### ISSUE THREAD

**Issue by DmitryFillo** [qubyte/fetch-ponyfill#21]
fetch-ponyfill always acts as a wrapper for XHR in the browser, but better to use native fetch if it's available. Seems like [these lines](https://github.com/qubyte/fetch-ponyfill/blob/master/fetch-browser.js#L10-L15) always forces to use polyfill, why are they needed?

**Comment by qubyte** [comment]
This behaviour is deliberate. The onus is on the developer consuming this library to do feature detection for fetch if that is what they want. The behaviour of this library should be the same regardless of the native support for fetch.

You can get the behaviour you'd like by doing:

```javascript
var fetch = self.fetch || require('fetch-ponyfill');
```

Should this library return native fetch when found, the option to ignore native fetch (perhaps for consistency) would be unavailable, or would need to added as an option. Neither of those is appealing in my opinion.

**Comment by DmitryFillo** [comment]
It sounds reasonable for me, thanks.

**Comment by arb** [comment]
I just stumbled upon this issue myself. I think this could be clarified in the readme. I was assuming I would be getting native fetch in browsers that had it.

**Comment by qubyte** [comment]
This is part of what it means to be a [ponyfill](https://github.com/sindresorhus/ponyfill). From that document:

> **Ponyfills should never use the native API, even if available**, as it might have slightly different behavior between environments, which can cause bugs.

(emphasis theirs)

That said, I'd be happy to include a little more information in the readme to make this facet of ponyfill behaviour more obvious. Pull requests happily considered!

**Comment by arb** [comment]
Ah... okay. Didn't drill down that far into the ponyfill doc.
