### ISSUE TITLE
Update dependency minimist > v1.2.3

### ISSUE THREAD

**Issue by Master-Guy** [qubyte/fetch-ponyfill#245]
Package minimist had Prototype pollution bug in versions previous to v1.2.3: https://github.com/substack/minimist

mkdirp 0.5.1 is having a dependency on minimist.
Please update your package to include a new version of mkdirp (maintained by @isaacs/node-mkdirp) or if you follow ESLint, remove mkdirp completely.

**Comment by qubyte** [comment]
The affected dependency was updated in #244. Since only development dependencies were affected there's no need to publish those changes to npm.
