### ISSUE TITLE
webpack issue

### ISSUE THREAD

**Issue by Lazyshot** [qubyte/fetch-ponyfill#249]
Currently there is an outstanding issue with webpack and node-fetch:

https://github.com/node-fetch/node-fetch/issues/450

The suggested workaround is `var fetch = require("node-fetch").default;` instead of just `var fetch = require('node-fetch')`

Also saw this was mentioned in #227 and #192

My specific reason for this issue is because it is required to use webpack for netlify lambda functions and a couple libraries I rely on are upstream dependents.

**Comment by Lazyshot** [comment]
Also saw this was mentioned in #227

**Comment by d-fischer** [comment]
#239 might have fixed this; care to confirm?

**Comment by Lazyshot** [comment]
Strangely enough, you own my dependency (https://github.com/d-fischer/twitch), so I'll take your word for it and move over there. Appreciated.
