### ISSUE TITLE
IE11 preProcessedHeaders.split(/\r?\n/) 

### ISSUE THREAD

**Issue by mikekotikov** [qubyte/fetch-ponyfill#253]
Thanks a lot for the ponyfill =)

Experience one issue on IE11 that crushes my app.

![image](https://user-images.githubusercontent.com/54106407/105077528-b3552880-5a9d-11eb-9c8e-40b30df8e845.png)

Have noticed that it fails with 'core-js' version above 3.5.0.
As for code investigation error appeared to raise at this expression to me `preProcessedHeaders.split(/\r?\n/) `.

Found [same problem description](https://github.com/github/fetch/issues/748) in 'fetch' repo and [PR with solution](https://github.com/github/fetch/pull/852) to it that worked fine in my case too.

Could you please apply this fix?

**Comment by qubyte** [comment]
Thanks for this. I've bumped fetch and published as 7.1.0.
