### ISSUE TITLE
Adding support for using cookies with node-fetch

### ISSUE THREAD

**Issue by amarzavery** [qubyte/fetch-ponyfill#33]
I love this library. It helps me build isomorphic javascript clients without polluting the global space. Thanks for the good work.

I wanted to use cookies for node-fetch in some of the scenarios. There is a package named [fetch-cookie](https://www.npmjs.com/package/fetch-cookie) that works well with node-fetch.
It would be nice if this can be exposed via `options: { useCookie : true|false }`.
if the user needs cookie support then in fetch-node.js we could wrap node-fetch inside fetch-cookie, otherwise it would be business as usual. 
```javascript
'use strict';

var fetch = require('node-fetch');

function wrapFetchForNode(fetch) {
  // Support schemaless URIs on the server for parity with the browser.
  // https://github.com/matthew-andrews/isomorphic-fetch/pull/10
  return function (u, options) {
    if (fetch && fetch.Request && u instanceof fetch.Request) { //<<<<<<<<<<<<<<<<<<<<<<<<<<
      return fetch(u, options);
    }

    var url = u.slice(0, 2) === '//' ? 'https:' + u : u;

    return fetch(url, options);
  };
}

module.exports = function (context) {
  // This modifies the global `node-fetch` object, which isn't great, since
  // different callers to `fetch-ponyfill` which pass a different Promise
  // implementation would each expect to have their implementation used. But,
  // given the way `node-fetch` is implemented, this is the only way to make
  // it work at all.
  if (context) {
    if (context.Promise) {
      fetch.Promise = context.Promise;
    }
    if (context.useCookie) {
      fetch = require('fetch-cookie')(fetch); //<<<<<<<<<<<<<<<<<<
    }
  }

  return {
    fetch: wrapFetchForNode(fetch),
    Headers: fetch.Headers,
    Request: fetch.Request,
    Response: fetch.Response
  };
};
```

**Comment by amarzavery** [comment]
@qubyte - Pinging to bring this to your attention.

**Comment by qubyte** [comment]
Yup, don't worry. I'm under a heavy workload at the moment, so this may take a few days for me to get to.

**Comment by sledorze** [comment]
@qubyte @amarzavery Is that issue inactive?

**Comment by qubyte** [comment]
There's an open PR for it (#37). I've been waiting for more interest in it though, since I'm not entirely happy adding ever more dependencies to this module, and it may break some behaviour around relative requests.
