### ISSUE TITLE
Adding Typescript Type Declaration File

### ISSUE THREAD

**Issue by smonusbonus** [qubyte/fetch-ponyfill#53]
Hello! I'm trying to use your module as part of a typescript project, but unfortunately it is missing a Typescript type declaration. I added the module like this to my code (I'm using webpack):

`import { fetch } from "fetch-ponyfill";`

But I'm getting the following error when trying to compile Typescript to JS: 

`(9,23): error TS7016: Could not find a declaration file for module 'fetch-ponyfill'. '/Users/simon.kreiser/Development/frontend/node_modules/fetch-ponyfill/fetch-node.js' implicitly has an 'any' type.`

Would you be interested in adding Typescript support? I'd be willing to help out or contribute. I'm relatively new to typescript, but I found this tutorial on how to write d.ts. files: https://blogs.msdn.microsoft.com/typescript/2016/12/14/writing-dts-files-for-types/

**Comment by paulmelnikow** [comment]
I've started playing around with TypeScript and would be happy to help with this, too.

**Comment by qubyte** [comment]
It might be possible to borrow the typescript definition to whatwg-fetch and augment it slightly. 🤔
